-- Supabase SQL: create history table for per-Gmail saved chats
-- Run in Supabase Dashboard → SQL Editor → New query → Paste → Run
create table if not exists public.history (
  id bigint generated by default as identity primary key,
  user_email text not null,
  question text not null,
  answer text not null,
  sources jsonb default '[]'::jsonb,
  created_at timestamp with time zone default now()
);
alter table public.history enable row level security;
-- For demo: allow all (use policies for production)
create policy "Allow all for demo" on public.history for all using (true) with check (true);
create index if not exists idx_history_email_created on public.history (user_email, created_at desc);
